class InternalError(Exception):
    pass


class PaymentFailedError(InternalError):
    pass
